# Generated by Django 3.2.5 on 2021-07-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diyproject',
            name='name',
        ),
    ]
