# Generated by Django 3.2.5 on 2021-07-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diyproject',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='diyproject',
            name='level',
            field=models.CharField(choices=[('h', 'hobbie'), ('i', 'intermediate'), ('a', 'advance')], default='s', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='level',
            field=models.CharField(choices=[('h', 'hobbie'), ('i', 'intermediate'), ('a', 'advance')], default='b', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='level',
            field=models.CharField(choices=[('h', 'hobbie'), ('i', 'intermediate'), ('a', 'advance')], default='b', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
