# Generated by Django 3.2.5 on 2021-07-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0004_auto_20210708_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diyproject',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='blogdiy.Skills'),
        ),
        migrations.AlterField(
            model_name='diyproject',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='blogdiy.DiyTask'),
        ),
    ]
