# Generated by Django 3.2.5 on 2021-07-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdiy', '0005_auto_20210708_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diyproject',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='diytask',
            name='owner',
        ),
    ]
