# Generated by Django 3.2.5 on 2021-07-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210708_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='joined_date',
        ),
        migrations.AddField(
            model_name='bloger',
            name='level',
            field=models.CharField(choices=[('h', 'hobbie'), ('i', 'intermediate'), ('a', 'advance')], default='h', max_length=50),
            preserve_default=False,
        ),
    ]
